const GET_DATA = "GET_DATA";
const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
const GET_DATA_FAILED = "GET_DATA_FAILED";

const GET_DETAIL = "GET_DETAIL";
const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
const GET_DETAIL_FAILED = "GET_DETAIL_FAILED";

const SET_SEARCH_RESULT = "SET_SEARCH_RESULT";

const FILTER_DATE = "FILTER_DATE";

const RESET_FILTER = "RESET_FILTER";

export{
    GET_DATA,
    GET_DATA_SUCCESS,
    GET_DATA_FAILED,
    GET_DETAIL,
    GET_DETAIL_SUCCESS,
    GET_DETAIL_FAILED,
    SET_SEARCH_RESULT,
    FILTER_DATE,
    RESET_FILTER,
}